# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='添加显示在首页的封面图', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='封面图'),
        ),
    ]
