# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpage_feed_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
