# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170908_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='allow_comments',
        ),
    ]
