# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpage_allow_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='publish',
        ),
    ]
