# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('blog', '0011_contactpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
