# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, height_field=30, null=True, upload_to='users/%Y/%m', verbose_name='头像', width_field=300),
        ),
    ]
