# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170914_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
