# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments_xtd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('subject', models.CharField(blank=True, max_length=20, verbose_name='专业')),
                ('message', models.TextField(verbose_name='消息')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布日期')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MyComment',
            fields=[
                ('xtdcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments_xtd.XtdComment')),
                ('qq_num', models.IntegerField(blank=True, null=True, verbose_name='QQ号')),
            ],
            options={
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'verbose_name': 'comment',
                'abstract': False,
                'verbose_name_plural': 'comments',
            },
            bases=('django_comments_xtd.xtdcomment',),
        ),
    ]
