# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0005_auto_20170920_2358'),
        ('mycomment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyComment',
            fields=[
                ('xtdcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments_xtd.XtdComment')),
                ('qq_num', models.IntegerField(blank=True, null=True, verbose_name='QQ号')),
            ],
            options={
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
            bases=('django_comments_xtd.xtdcomment',),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
